"""empty message

Revision ID: 49a88cdbb9e4
Revises: 
Create Date: 2024-09-02 11:12:25.051361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a88cdbb9e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('country', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parsedsite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_parsed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('processory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('lineup', sa.String(length=20), nullable=True),
    sa.Column('socket', sa.String(length=15), nullable=False),
    sa.Column('tech_process', sa.String(length=6), nullable=True),
    sa.Column('equipment', sa.String(length=3), nullable=False),
    sa.Column('clock_frequency', sa.Float(), nullable=True),
    sa.Column('turboboost_frequency', sa.Float(), nullable=True),
    sa.Column('cores_amount', sa.Integer(), nullable=True),
    sa.Column('productive_cores_amount', sa.Integer(), nullable=True),
    sa.Column('energy_efficient_cores_amount', sa.Integer(), nullable=True),
    sa.Column('threads_amount', sa.Integer(), nullable=True),
    sa.Column('tdp', sa.String(length=6), nullable=True),
    sa.Column('second_level_cache', sa.String(length=10), nullable=True),
    sa.Column('third_level_cache', sa.String(length=10), nullable=True),
    sa.Column('free_multiplier', sa.String(length=3), nullable=True),
    sa.Column('RAM_support', sa.String(length=4), nullable=True),
    sa.Column('graphics_core', sa.String(length=4), nullable=True),
    sa.CheckConstraint('2 < tech_process <= 65'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('processoryprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processory_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['processory_id'], ['processory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processory_id', 'city_id', name='_product_city_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processoryprice')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('processory')
    op.drop_table('parsedsite')
    op.drop_table('city')
    # ### end Alembic commands ###
