"""empty message

Revision ID: 6b81e83a9133
Revises: 87635f22e2e6
Create Date: 2024-09-15 15:25:13.764896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b81e83a9133'
down_revision: Union[str, None] = '87635f22e2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processoryprice', schema=None) as batch_op:
        batch_op.drop_constraint('_store_city_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processoryprice', schema=None) as batch_op:
        batch_op.create_unique_constraint('_store_city_uc', ['store', 'city_id'])

    # ### end Alembic commands ###
